name: Get Citation Data 2019

on:
  schedule:
    - cron: '40 8 * * *'
  workflow_dispatch:
  workflow_run:
    workflows: ['Get Citation Data 2018']
    types: [completed]

jobs:
  build:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Reqs
        run: |
          sudo apt-get install -y python3-setuptools
      - name: Run 2019
        env:
          GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
        run: |
          cd ./google_scholar_crawler
          pip3 install -r requirements.txt
          python3 main_by_year.py --year 2019
          python3 pubs_pre_by_year.py --year 2019 --src ../results/gs_data_2019.json --out ../results/all_publications_2019.csv
          python3 selected_pubs_by_year.py --year 2019 --csv ../results/all_publications_2019.csv
          cd ../results
          git init
          git config --local user.name "${{ github.repository_owner }}"
          git config --local user.email "${{ github.repository_owner }}@users.noreply.github.com"
          export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git add .
          git commit -m "Updated Citation Data (2019)"
          git push "${remote_repo}" HEAD:google-scholar-stats-2019 --force
