name: Get Citation Data 2025

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Reqs
        run: |
          sudo apt-get install -y python3-setuptools
      - name: Run 2025
        env:
          GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
        run: |
          cd ./google_scholar_crawler
          pip3 install -r requirements.txt
          python3 pubs_pre_by_year.py --year 2025 --out ../results/all_publications_2025.csv
          python3 selected_pubs_by_year.py --year 2025 --csv ../results/all_publications_2025.csv
          python3 selected_pubs_2025.py
          cd ./results
          git init
          git config --local user.name "${GITHUB_ACTOR}"
          export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git add .
          git commit -m "Updated Citation Data (2025)"
          git push "${remote_repo}" HEAD:google-scholar-stats-2025 --force
