name: Get Citation Data 2017

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Reqs
        run: |
          sudo apt-get install -y python3-setuptools
      - name: Run 2017
        env:
          GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
        run: |
          cd ./google_scholar_crawler
          pip3 install -r requirements.txt
          python3 main_by_year.py --year 2017
          python3 pubs_pre_by_year.py --year 2017 --src ../results/gs_data_2017.json --out ../results/all_publications_2017.csv
          python3 selected_pubs_by_year.py --year 2017 --csv ../results/all_publications_2017.csv
          cd ./results
          git init
          git config --local user.name "${{ github.repository_owner }}"
          git config --local user.email "${{ github.repository_owner }}@users.noreply.github.com"
          export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git add .
          git commit -m "Updated Citation Data (2017)"
          git push "${remote_repo}" HEAD:google-scholar-stats-2017 --force
