name: Get Citation Data 2020 Full Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Reqs
        run: |
          sudo apt-get install -y python3-setuptools
      - name: Run Full + 2020 only
        env:
          GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
        run: |
          set -e
          cd ./google_scholar_crawler
          pip3 install -r requirements.txt
          # Full crawl using legacy-like main.py
          python3 main.py
          # Preprocess and generate only for 2020 from full data
          python3 pubs_pre_by_year.py --year 2020 --out ../results/all_publications_2020.csv
          python3 selected_pubs_by_year.py --year 2020 --csv ../results/all_publications_2020.csv
          cd ./results
          git init
          git config --local user.name "${{ github.repository_owner }}"
          git config --local user.email "${{ github.repository_owner }}@users.noreply.github.com"
          export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git add .
          git commit -m "Updated Citation Data (2020 full test)"
          git push "${remote_repo}" HEAD:google-scholar-stats-2020-full --force
