name: Sync Scholar (All)

on:
  workflow_dispatch:
  schedule:
    - cron: '35 7 * * 1'  # weekly, Mon 07:35 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pinned deps (same as yearly)
        run: |
          pip3 install -r google_scholar_crawler/requirements.txt
      - name: Sync scholar (about-only quick pass)
        env:
          GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
        run: |
          python3 tools/sync_scholar_all.py --delay 1.0 --no-proxy --retries 1 --about-only
      - name: Commit changes (main)
        run: |
          git config --local user.name "${{ github.repository_owner }}"
          git config --local user.email "${{ github.repository_owner }}@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add results/
            git commit -m "chore(sync): update results from Scholar (all)"
            git push
          else
            echo "No changes to commit"
          fi
